[project]
name = "ssemcpservers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.15"
dependencies = [
    "black==25.11.0",
    "flake8==7.3.0",
    "isort==7.0.0",
    "mypy==1.19.0",
    "oxygent==1.0.8",
    "pytest==9.0.1",
]
